// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApp1.Models;

public partial class LocalDBMSSQLLocalDBContext : DbContext
{
    public LocalDBMSSQLLocalDBContext()
    {
    }

    public LocalDBMSSQLLocalDBContext(DbContextOptions<LocalDBMSSQLLocalDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<Rank> Ranks { get; set; }

    public virtual DbSet<Soldier> Soldiers { get; set; }

    public virtual DbSet<SoldierPosition> SoldierPositions { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"C:\\Users\\doruu\\AppData\\Local\\Microsoft\\Microsoft SQL Server Local DB\\Instances\\MSSQLLocalDB\\test.mdf\";Integrated Security=True;Connect Timeout=30;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Country>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07D0135C53");

            entity.ToTable("Country");

            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<Rank>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07BC2807C0");

            entity.ToTable("Rank");

            entity.Property(e => e.Description).HasMaxLength(50);
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<Soldier>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC072F6742A6");

            entity.ToTable("Soldier");

            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.Training).HasMaxLength(50);

            entity.HasOne(d => d.Country).WithMany(p => p.Soldiers)
                .HasForeignKey(d => d.CountryId)
                .HasConstraintName("FK_Soldier_Country");

            entity.HasOne(d => d.Rank).WithMany(p => p.Soldiers)
                .HasForeignKey(d => d.RankId)
                .HasConstraintName("FK_Soldier_Rank");
        });

        modelBuilder.Entity<SoldierPosition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SoldierP__3214EC0782AC3AAB");

            entity.ToTable("SoldierPosition");

            entity.Property(e => e.Position).HasMaxLength(50);

            entity.HasOne(d => d.Soldier).WithMany(p => p.SoldierPositions)
                .HasForeignKey(d => d.SoldierId)
                .HasConstraintName("FK_SoldierPosition_Soldier");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}