// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp1.Models;

public partial class Soldier
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? RankId { get; set; }

    public int? CountryId { get; set; }

    public string Training { get; set; }

    public virtual Country Country { get; set; }

    public virtual Rank Rank { get; set; }

    public virtual ICollection<SoldierPosition> SoldierPositions { get; set; } = new List<SoldierPosition>();
}