// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp1.Models;

public partial class SoldierPosition
{
    public int Id { get; set; }

    public int? SoldierId { get; set; }

    public string Position { get; set; }

    public virtual Soldier Soldier { get; set; }
}